// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"binance_dai_admin/internal/biz"
	"binance_dai_admin/internal/conf"
	"binance_dai_admin/internal/data"
	"binance_dai_admin/internal/server"
	"binance_dai_admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	userdataRepo := data.NewUserdataRepo(dataData, logger)
	transaction := data.NewTransaction(dataData)
	userdataUsecase := biz.NewUserdataUsecase(userdataRepo, transaction, logger)
	userdataService := service.NewUserdataService(userdataUsecase)
	httpServer := server.NewHTTPServer(confServer, userdataService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
