// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.7
// source: api/userdata/v1/userdata.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Userdata_GetUserOrders_FullMethodName = "/api.userdata.v1.Userdata/GetUserOrders"
)

// UserdataClient is the client API for Userdata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserdataClient interface {
	GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...grpc.CallOption) (*GetUserOrdersReply, error)
}

type userdataClient struct {
	cc grpc.ClientConnInterface
}

func NewUserdataClient(cc grpc.ClientConnInterface) UserdataClient {
	return &userdataClient{cc}
}

func (c *userdataClient) GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...grpc.CallOption) (*GetUserOrdersReply, error) {
	out := new(GetUserOrdersReply)
	err := c.cc.Invoke(ctx, Userdata_GetUserOrders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserdataServer is the server API for Userdata service.
// All implementations must embed UnimplementedUserdataServer
// for forward compatibility
type UserdataServer interface {
	GetUserOrders(context.Context, *GetUserOrdersRequest) (*GetUserOrdersReply, error)
	mustEmbedUnimplementedUserdataServer()
}

// UnimplementedUserdataServer must be embedded to have forward compatible implementations.
type UnimplementedUserdataServer struct {
}

func (UnimplementedUserdataServer) GetUserOrders(context.Context, *GetUserOrdersRequest) (*GetUserOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrders not implemented")
}
func (UnimplementedUserdataServer) mustEmbedUnimplementedUserdataServer() {}

// UnsafeUserdataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserdataServer will
// result in compilation errors.
type UnsafeUserdataServer interface {
	mustEmbedUnimplementedUserdataServer()
}

func RegisterUserdataServer(s grpc.ServiceRegistrar, srv UserdataServer) {
	s.RegisterService(&Userdata_ServiceDesc, srv)
}

func _Userdata_GetUserOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserdataServer).GetUserOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userdata_GetUserOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserdataServer).GetUserOrders(ctx, req.(*GetUserOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Userdata_ServiceDesc is the grpc.ServiceDesc for Userdata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Userdata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.userdata.v1.Userdata",
	HandlerType: (*UserdataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserOrders",
			Handler:    _Userdata_GetUserOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/userdata/v1/userdata.proto",
}
