// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.7
// source: api/userdata/v1/userdata.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserOrdersRequest) Reset() {
	*x = GetUserOrdersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersRequest) ProtoMessage() {}

func (x *GetUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{0}
}

type GetUserOrdersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64 `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (x *GetUserOrdersReply) Reset() {
	*x = GetUserOrdersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserOrdersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersReply) ProtoMessage() {}

func (x *GetUserOrdersReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersReply.ProtoReflect.Descriptor instead.
func (*GetUserOrdersReply) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserOrdersReply) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type PullUserIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullUserIncomeRequest) Reset() {
	*x = PullUserIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullUserIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullUserIncomeRequest) ProtoMessage() {}

func (x *PullUserIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullUserIncomeRequest.ProtoReflect.Descriptor instead.
func (*PullUserIncomeRequest) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{2}
}

type PullUserIncomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullUserIncomeReply) Reset() {
	*x = PullUserIncomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullUserIncomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullUserIncomeReply) ProtoMessage() {}

func (x *PullUserIncomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullUserIncomeReply.ProtoReflect.Descriptor instead.
func (*PullUserIncomeReply) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{3}
}

type GetUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{4}
}

type GetUsersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*GetUsersReply_DataList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetUsersReply) Reset() {
	*x = GetUsersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersReply) ProtoMessage() {}

func (x *GetUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersReply.ProtoReflect.Descriptor instead.
func (*GetUsersReply) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersReply) GetList() []*GetUsersReply_DataList {
	if x != nil {
		return x.List
	}
	return nil
}

type GetUsersIncomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Start  int64  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End    int64  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *GetUsersIncomeRequest) Reset() {
	*x = GetUsersIncomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersIncomeRequest) ProtoMessage() {}

func (x *GetUsersIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersIncomeRequest.ProtoReflect.Descriptor instead.
func (*GetUsersIncomeRequest) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersIncomeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUsersIncomeRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetUsersIncomeRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type GetUsersIncomeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*GetUsersIncomeReply_DataList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetUsersIncomeReply) Reset() {
	*x = GetUsersIncomeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersIncomeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersIncomeReply) ProtoMessage() {}

func (x *GetUsersIncomeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersIncomeReply.ProtoReflect.Descriptor instead.
func (*GetUsersIncomeReply) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsersIncomeReply) GetList() []*GetUsersIncomeReply_DataList {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateUserNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Num    float64 `protobuf:"fixed64,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *UpdateUserNumRequest) Reset() {
	*x = UpdateUserNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserNumRequest) ProtoMessage() {}

func (x *UpdateUserNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserNumRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserNumRequest) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserNumRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserNumRequest) GetNum() float64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type UpdateUserNumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateUserNumReply) Reset() {
	*x = UpdateUserNumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserNumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserNumReply) ProtoMessage() {}

func (x *UpdateUserNumReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserNumReply.ProtoReflect.Descriptor instead.
func (*UpdateUserNumReply) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{9}
}

type GetNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNumRequest) Reset() {
	*x = GetNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumRequest) ProtoMessage() {}

func (x *GetNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumRequest.ProtoReflect.Descriptor instead.
func (*GetNumRequest) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{10}
}

type GetNumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*GetNumReply_DataList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetNumReply) Reset() {
	*x = GetNumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumReply) ProtoMessage() {}

func (x *GetNumReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumReply.ProtoReflect.Descriptor instead.
func (*GetNumReply) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{11}
}

func (x *GetNumReply) GetList() []*GetNumReply_DataList {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string  `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Num    float64 `protobuf:"fixed64,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *UpdateNumRequest) Reset() {
	*x = UpdateNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNumRequest) ProtoMessage() {}

func (x *UpdateNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNumRequest.ProtoReflect.Descriptor instead.
func (*UpdateNumRequest) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateNumRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UpdateNumRequest) GetNum() float64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type UpdateNumReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateNumReply) Reset() {
	*x = UpdateNumReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNumReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNumReply) ProtoMessage() {}

func (x *UpdateNumReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNumReply.ProtoReflect.Descriptor instead.
func (*UpdateNumReply) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{13}
}

type GetUsersReply_DataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	UserId uint64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Ip     string  `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Num    float64 `protobuf:"fixed64,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GetUsersReply_DataList) Reset() {
	*x = GetUsersReply_DataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersReply_DataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersReply_DataList) ProtoMessage() {}

func (x *GetUsersReply_DataList) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersReply_DataList.ProtoReflect.Descriptor instead.
func (*GetUsersReply_DataList) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetUsersReply_DataList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUsersReply_DataList) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUsersReply_DataList) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetUsersReply_DataList) GetNum() float64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type GetUsersIncomeReply_DataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Income string `protobuf:"bytes,3,opt,name=income,proto3" json:"income,omitempty"`
	Time   string `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *GetUsersIncomeReply_DataList) Reset() {
	*x = GetUsersIncomeReply_DataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersIncomeReply_DataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersIncomeReply_DataList) ProtoMessage() {}

func (x *GetUsersIncomeReply_DataList) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersIncomeReply_DataList.ProtoReflect.Descriptor instead.
func (*GetUsersIncomeReply_DataList) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetUsersIncomeReply_DataList) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetUsersIncomeReply_DataList) GetIncome() string {
	if x != nil {
		return x.Income
	}
	return ""
}

func (x *GetUsersIncomeReply_DataList) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type GetNumReply_DataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey string  `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Num    float64 `protobuf:"fixed64,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GetNumReply_DataList) Reset() {
	*x = GetNumReply_DataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_userdata_v1_userdata_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNumReply_DataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumReply_DataList) ProtoMessage() {}

func (x *GetNumReply_DataList) ProtoReflect() protoreflect.Message {
	mi := &file_api_userdata_v1_userdata_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumReply_DataList.ProtoReflect.Descriptor instead.
func (*GetNumReply_DataList) Descriptor() ([]byte, []int) {
	return file_api_userdata_v1_userdata_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetNumReply_DataList) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetNumReply_DataList) GetNum() float64 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_api_userdata_v1_userdata_proto protoreflect.FileDescriptor

var file_api_userdata_v1_userdata_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x76,
	0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x75, 0x6c, 0x6c, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x15, 0x0a, 0x13, 0x50, 0x75, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x58, 0x0a, 0x08, 0x44, 0x61, 0x74,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x22, 0x57, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0xa8, 0x01, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x41, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x4e, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x63,
	0x6f, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x7e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x39, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x34, 0x0a, 0x08, 0x44, 0x61,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x22, 0x3c, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x10,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x32, 0xaf, 0x07, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x12, 0x8b, 0x01,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2e, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x28, 0x12, 0x26, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x64, 0x61, 0x69, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x67, 0x65, 0x74, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x90, 0x01, 0x0a, 0x0e,
	0x50, 0x75, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x26,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x30, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x2a, 0x12, 0x28, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x5f, 0x64, 0x61, 0x69, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x70, 0x75, 0x6c,
	0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x12, 0x76,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x28, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x22, 0x12, 0x20, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x5f, 0x64, 0x61, 0x69, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x67, 0x65, 0x74,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x8f, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x29, 0x12,
	0x27, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x61,
	0x69, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x8b, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x75,
	0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x12, 0x26,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x69,
	0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x12, 0x6e, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d,
	0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x12, 0x1e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x69, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x67,
	0x65, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x12, 0x7a, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4e, 0x75, 0x6d, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x12,
	0x21, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x61,
	0x69, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x42, 0x39, 0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x24, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x64, 0x61, 0x69, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_userdata_v1_userdata_proto_rawDescOnce sync.Once
	file_api_userdata_v1_userdata_proto_rawDescData = file_api_userdata_v1_userdata_proto_rawDesc
)

func file_api_userdata_v1_userdata_proto_rawDescGZIP() []byte {
	file_api_userdata_v1_userdata_proto_rawDescOnce.Do(func() {
		file_api_userdata_v1_userdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_userdata_v1_userdata_proto_rawDescData)
	})
	return file_api_userdata_v1_userdata_proto_rawDescData
}

var file_api_userdata_v1_userdata_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_userdata_v1_userdata_proto_goTypes = []interface{}{
	(*GetUserOrdersRequest)(nil),         // 0: api.userdata.v1.GetUserOrdersRequest
	(*GetUserOrdersReply)(nil),           // 1: api.userdata.v1.GetUserOrdersReply
	(*PullUserIncomeRequest)(nil),        // 2: api.userdata.v1.PullUserIncomeRequest
	(*PullUserIncomeReply)(nil),          // 3: api.userdata.v1.PullUserIncomeReply
	(*GetUsersRequest)(nil),              // 4: api.userdata.v1.GetUsersRequest
	(*GetUsersReply)(nil),                // 5: api.userdata.v1.GetUsersReply
	(*GetUsersIncomeRequest)(nil),        // 6: api.userdata.v1.GetUsersIncomeRequest
	(*GetUsersIncomeReply)(nil),          // 7: api.userdata.v1.GetUsersIncomeReply
	(*UpdateUserNumRequest)(nil),         // 8: api.userdata.v1.UpdateUserNumRequest
	(*UpdateUserNumReply)(nil),           // 9: api.userdata.v1.UpdateUserNumReply
	(*GetNumRequest)(nil),                // 10: api.userdata.v1.GetNumRequest
	(*GetNumReply)(nil),                  // 11: api.userdata.v1.GetNumReply
	(*UpdateNumRequest)(nil),             // 12: api.userdata.v1.UpdateNumRequest
	(*UpdateNumReply)(nil),               // 13: api.userdata.v1.UpdateNumReply
	(*GetUsersReply_DataList)(nil),       // 14: api.userdata.v1.GetUsersReply.DataList
	(*GetUsersIncomeReply_DataList)(nil), // 15: api.userdata.v1.GetUsersIncomeReply.DataList
	(*GetNumReply_DataList)(nil),         // 16: api.userdata.v1.GetNumReply.DataList
}
var file_api_userdata_v1_userdata_proto_depIdxs = []int32{
	14, // 0: api.userdata.v1.GetUsersReply.list:type_name -> api.userdata.v1.GetUsersReply.DataList
	15, // 1: api.userdata.v1.GetUsersIncomeReply.list:type_name -> api.userdata.v1.GetUsersIncomeReply.DataList
	16, // 2: api.userdata.v1.GetNumReply.list:type_name -> api.userdata.v1.GetNumReply.DataList
	0,  // 3: api.userdata.v1.Userdata.GetUserOrders:input_type -> api.userdata.v1.GetUserOrdersRequest
	2,  // 4: api.userdata.v1.Userdata.PullUserIncome:input_type -> api.userdata.v1.PullUserIncomeRequest
	4,  // 5: api.userdata.v1.Userdata.GetUsers:input_type -> api.userdata.v1.GetUsersRequest
	6,  // 6: api.userdata.v1.Userdata.GetUsersIncome:input_type -> api.userdata.v1.GetUsersIncomeRequest
	8,  // 7: api.userdata.v1.Userdata.UpdateUserNum:input_type -> api.userdata.v1.UpdateUserNumRequest
	10, // 8: api.userdata.v1.Userdata.GetNum:input_type -> api.userdata.v1.GetNumRequest
	12, // 9: api.userdata.v1.Userdata.UpdateNum:input_type -> api.userdata.v1.UpdateNumRequest
	1,  // 10: api.userdata.v1.Userdata.GetUserOrders:output_type -> api.userdata.v1.GetUserOrdersReply
	3,  // 11: api.userdata.v1.Userdata.PullUserIncome:output_type -> api.userdata.v1.PullUserIncomeReply
	5,  // 12: api.userdata.v1.Userdata.GetUsers:output_type -> api.userdata.v1.GetUsersReply
	7,  // 13: api.userdata.v1.Userdata.GetUsersIncome:output_type -> api.userdata.v1.GetUsersIncomeReply
	9,  // 14: api.userdata.v1.Userdata.UpdateUserNum:output_type -> api.userdata.v1.UpdateUserNumReply
	11, // 15: api.userdata.v1.Userdata.GetNum:output_type -> api.userdata.v1.GetNumReply
	13, // 16: api.userdata.v1.Userdata.UpdateNum:output_type -> api.userdata.v1.UpdateNumReply
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_userdata_v1_userdata_proto_init() }
func file_api_userdata_v1_userdata_proto_init() {
	if File_api_userdata_v1_userdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_userdata_v1_userdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserOrdersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullUserIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullUserIncomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersIncomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersIncomeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserNumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNumReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersReply_DataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersIncomeReply_DataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_userdata_v1_userdata_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNumReply_DataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_userdata_v1_userdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_userdata_v1_userdata_proto_goTypes,
		DependencyIndexes: file_api_userdata_v1_userdata_proto_depIdxs,
		MessageInfos:      file_api_userdata_v1_userdata_proto_msgTypes,
	}.Build()
	File_api_userdata_v1_userdata_proto = out.File
	file_api_userdata_v1_userdata_proto_rawDesc = nil
	file_api_userdata_v1_userdata_proto_goTypes = nil
	file_api_userdata_v1_userdata_proto_depIdxs = nil
}
