// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v3.21.7
// source: api/userdata/v1/userdata.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserdataGetUserOrders = "/api.userdata.v1.Userdata/GetUserOrders"

type UserdataHTTPServer interface {
	GetUserOrders(context.Context, *GetUserOrdersRequest) (*GetUserOrdersReply, error)
}

func RegisterUserdataHTTPServer(s *http.Server, srv UserdataHTTPServer) {
	r := s.Route("/")
	r.GET("/api/binance_dai_admin/get_user_orders", _Userdata_GetUserOrders0_HTTP_Handler(srv))
}

func _Userdata_GetUserOrders0_HTTP_Handler(srv UserdataHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserdataGetUserOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserOrders(ctx, req.(*GetUserOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserOrdersReply)
		return ctx.Result(200, reply)
	}
}

type UserdataHTTPClient interface {
	GetUserOrders(ctx context.Context, req *GetUserOrdersRequest, opts ...http.CallOption) (rsp *GetUserOrdersReply, err error)
}

type UserdataHTTPClientImpl struct {
	cc *http.Client
}

func NewUserdataHTTPClient(client *http.Client) UserdataHTTPClient {
	return &UserdataHTTPClientImpl{client}
}

func (c *UserdataHTTPClientImpl) GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...http.CallOption) (*GetUserOrdersReply, error) {
	var out GetUserOrdersReply
	pattern := "/api/binance_dai_admin/get_user_orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserdataGetUserOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
